/**
* Created by Jason Ablott on 3/3/25.
*/

#include "expr.h"
#include "val.h"
#include "catch.h"
#include <string>


// NumVal Methods



// NumVal constructor
NumVal::NumVal(int intValue) {
    this->intValue = intValue;
}

// NumVal equals method
bool NumVal::equals(PTR(Val) other) const {
    PTR(NumVal) num = CAST(NumVal)(other);
    if (num == nullptr) return false;
    return this->intValue == num->intValue;
}

// addTo method for NumVals
PTR(Val) NumVal::addTo(PTR(Val) other) {
    PTR(NumVal) num = CAST(NumVal)(other);
    if (num == nullptr) return nullptr; // slide 46
    return NEW(NumVal)((unsigned)this->intValue + (unsigned)num->intValue);
}

// multWith method for NumVals
PTR(Val) NumVal::multWith(PTR(Val) other) {
    PTR(NumVal) num = CAST(NumVal)(other);
    if (num == nullptr) return nullptr;
    return NEW(NumVal)((unsigned)this->intValue * (unsigned)num->intValue);
}

// to string method for NumVal
std::string NumVal::toString() const {
    return std::to_string(this->intValue);
}

// // to expr method for NumVal
// PTR(Expr) NumVal::toExpr() const {
//     return NEW(NumExpr)(this->intValue);
// }

// returns whether this value is true for BoolVals
bool NumVal::isTrue() {
    throw std::runtime_error("a number cannot be true");
}

// Calls a numVal
PTR(Val) NumVal::call(PTR(Val)actual_arg) {
    throw std::runtime_error("Cannot call a number value");
}



// BoolVal Methods



// BoolVal object constructor
BoolVal::BoolVal(bool boolValue) {
    this->boolValue = boolValue;
}

// determines equality between two BoolVal objects
bool BoolVal::equals(PTR(Val) other) const{
    PTR(BoolVal) otherBool = CAST(BoolVal)(other);
    if (otherBool == nullptr) return false;
    return this->boolValue == otherBool->boolValue;
}

// adds two BoolVal objects, always throws an exception
PTR(Val) BoolVal::addTo(PTR(Val) other) {
    throw std::runtime_error("Cannot add a boolean value");
}

// multiplies two BoolVal objects, always throws an exception
PTR(Val) BoolVal::multWith(PTR(Val) other) {
    throw std::runtime_error("Cannot multiply a boolean value");
}

// converts this BoolVal to a string
std::string BoolVal::toString() const {
    //return std::to_string(this->boolValue);
    return this->boolValue ? "true" : "false";
}

// // converts this BoolVal to a BoolExpr
// PTR(Expr) BoolVal::toExpr() const {
//     // implement BoolExpr class then this will work
//     return NEW(BoolExpr)(this->boolValue);
//     //return nullptr;
// }

// returns whether this value is true for BoolVals
bool BoolVal::isTrue() {
    return this->boolValue;
}

// calls this BoolVal on an actual argument via substitution, always throws an exception
PTR(Val) BoolVal::call(PTR(Val) actual_arg) {
    throw std::runtime_error("Cannot call a boolean value");
}



// FunVal Methods



// brief FunVal object constructor
FunVal::FunVal(std::string formal_arg, PTR(Expr) body, PTR(Env) env) {
    this->formal_arg = formal_arg;
    this->body = body;
    this->env = env;
}

// brief determines equality between two FunVal objects
bool FunVal::equals(PTR(Val) other) const {
    if (CAST(FunVal)(other) == nullptr) return false;
    if (this->formal_arg == CAST(FunVal)(other)->formal_arg) {
        return this->body->equals(CAST(FunVal)(other)->body);
    }
    return false;
}

// brief adds two FunVal objects, always throws an exception
PTR(Val) FunVal::addTo(PTR(Val) other) {
    throw std::runtime_error("Cannot add a function value");
}

// brief multiplies two FunVal objects, always throws an exception
PTR(Val) FunVal::multWith(PTR(Val) other) {
    throw std::runtime_error("Cannot multiply a function value");
}

// converts this FunVal to a string
std::string FunVal::toString() const {
    std::string s = "_fun (";
    s += this->formal_arg;
    s += ") ";
    s += this->body->to_string();
    s += " ";
    return s;
}

// // converts this FunVal to a FunExpr
// PTR(Expr) FunVal::toExpr() const {
//     return NEW(FunExpr)(formal_arg, body);
// }

// returns whether this value is true for FunVals
bool FunVal::isTrue() {
    throw std::runtime_error("function value cannot be true");
}

// calls a FunVal
PTR(Val) FunVal::call (PTR(Val) actual_arg) {
    //PTR(Expr) act = actual_arg->toExpr();
    //return this->body->subst(this->formal_arg, act)->interp();
    return body->interp(NEW(ExtendedEnv)(formal_arg, actual_arg, Env::empty)); // TODO ????
}


// **** TEST CASES FOR NUMVAL GENERATED BY CHATGPT and reviewed/edited by me****



TEST_CASE("NumVal addition with valid NumVals") {
    // Create two NumVal objects with values 5 and 7
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(7);

    // Add them using the `addTo` method
    PTR(Val) result = num1->addTo(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is 12 (5 + 7)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "12");

    // Clean up the result object
    //delete result;
}

TEST_CASE("NumVal addition with zero") {
    // Test adding zero to a NumVal object
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(0);

    PTR(Val) result = num1->addTo(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is 5 (5 + 0)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "5");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal addition with negative numbers") {
    // Test adding a negative number
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(-3);

    PTR(Val) result = num1->addTo(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is 2 (5 + (-3))
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "2");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal adding two negative numbers") {
    // Test adding two negative numbers
    PTR(NumVal) num1 = NEW(NumVal)(-5);
    PTR(NumVal) num2 = NEW(NumVal)(-3);

    PTR(Val) result = num1->addTo(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is -8 (-5 + -3)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "-8");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal multiplication with valid NumVals") {
    // Create two NumVal objects with values 5 and 7
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(7);

    // Multiply them using the `multWith` method
    PTR(Val) result = num1->multWith(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is 35 (5 * 7)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "35");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal multiplication with zero") {
    // Test multiplying by zero
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(0);

    PTR(Val) result = num1->multWith(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is 0 (5 * 0)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "0");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal multiplication with negative numbers") {
    // Test multiplying by a negative number
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(-3);

    PTR(Val) result = num1->multWith(num2);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value is -15 (5 * -3)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "-15");

    // Clean up the result object
    // delete result;
}

TEST_CASE("NumVal equality check") {
    // Create two NumVal objects with equal values
    PTR(NumVal) num1 = NEW(NumVal)(5);
    PTR(NumVal) num2 = NEW(NumVal)(5);

    // Check if they are equal
    REQUIRE(num1->equals(num2) == true);

    // Create a NumVal with a different value
    PTR(NumVal) num3 = NEW(NumVal)(7);

    // Check if they are not equal
    REQUIRE(num1->equals(num3) == false);
}

TEST_CASE("NumVal toString method") {
    // Test the `toString` method
    NumVal num1(42);

    // Validate that the string representation is "42"
    REQUIRE(num1.toString() == "42");
}

// TEST_CASE("NumVal toExpr method") {
//     // Test the `toExpr` method, which should return a corresponding NumExpr
//     NumVal num1(42);
//
//     PTR(Expr) expr = num1.toExpr();
//     REQUIRE(CAST(NumExpr)(expr) != nullptr);
//
//     // Validate the expression value inside NumExpr is the same as the NumVal
//     PTR(NumExpr) numExpr = CAST(NumExpr)(expr);
//     REQUIRE(numExpr->val == 42);
//
//     // Clean up the created expression object
//     // delete expr;
// }


// **** TEST CASES FOR BOOLVAL GENERATED BY CHATGPT and reviewed/edited by me ****


TEST_CASE("BoolVal equality check") {
    // Create two BoolVal objects with equal values
    PTR(BoolVal) bool1 = NEW(BoolVal)(true);
    PTR(BoolVal) bool2 = NEW(BoolVal)(true);

    // Check if they are equal
    REQUIRE(bool1->equals(bool2) == true);

    // Create a BoolVal with a different value
    PTR(BoolVal) bool3 = NEW(BoolVal)(false);

    // Check if they are not equal
    REQUIRE(bool1->equals(bool3) == false);
}

TEST_CASE("BoolVal toString method") {
    // Test the `toString` method
    BoolVal boolVal(true);

    // Validate that the string representation is "true"
    REQUIRE(boolVal.toString() == "true");

    BoolVal boolVal2(false);

    // Validate that the string representation is "false"
    REQUIRE(boolVal2.toString() == "false");
}

TEST_CASE("BoolVal isTrue method") {
    // Test the `isTrue` method for true
    BoolVal boolValTrue(true);
    REQUIRE(boolValTrue.isTrue() == true);

    // Test the `isTrue` method for false
    BoolVal boolValFalse(false);
    REQUIRE(boolValFalse.isTrue() == false);
}

TEST_CASE("BoolVal addition throws exception") {
    // Test adding two BoolVal objects, which should always throw an exception
    PTR(BoolVal) boolVal1 = NEW(BoolVal)(true);
    PTR(BoolVal) boolVal2 = NEW(BoolVal)(false);

    REQUIRE_THROWS_AS(boolVal1->addTo(boolVal2), std::runtime_error);
}

TEST_CASE("BoolVal multiplication throws exception") {
    // Test multiplying two BoolVal objects, which should always throw an exception
    PTR(BoolVal) boolVal1 = NEW(BoolVal)(true);
    PTR(BoolVal) boolVal2 = NEW(BoolVal)(false);

    REQUIRE_THROWS_AS(boolVal1->multWith(boolVal2), std::runtime_error);
}

TEST_CASE("BoolVal equals with a NumVal object") {
    // Test comparing a BoolVal with a NumVal, which should return false
    PTR(BoolVal) boolVal = NEW(BoolVal)(true);
    PTR(NumVal) numVal = NEW(NumVal)(1);

    REQUIRE(boolVal->equals(numVal) == false);
}

TEST_CASE("BoolVal equals with a nullptr") {
    // Test comparing a BoolVal with nullptr, which should return false
    BoolVal boolVal(true);

    REQUIRE(boolVal.equals(nullptr) == false);
}


// **** TEST CASES FOR FUNVAL GENERATED BY CHATGPT and reviewed/edited by me****


TEST_CASE("FunVal equality check") {
    // Create two FunVal objects with equal values
    PTR(Expr) body1 = NEW(NumExpr)(5);
    PTR(Expr) body2 = NEW(NumExpr)(5);
    PTR(FunVal) fun1 = NEW(FunVal)("x", body1, Env::empty);
    PTR(FunVal) fun2 = NEW(FunVal)("x", body2, Env::empty);

    // Check if they are equal
    REQUIRE(fun1->equals(fun2) == true);

    // Create a FunVal with a different formal argument
    PTR(Expr) body3 = NEW(NumExpr)(10);
    PTR(FunVal) fun3 = NEW(FunVal)("y", body3, Env::empty);

    // Check if they are not equal
    REQUIRE(fun1->equals(fun3) == false);

    // Clean up the created expression objects
    // delete body1;
    // delete body2;
    // delete body3;
}

TEST_CASE("FunVal addition throws exception") {
    // Test adding two FunVal objects, which should always throw an exception
    PTR(Expr) body1 = NEW(NumExpr)(5);
    PTR(Expr) body2 = NEW(NumExpr)(10);
    PTR(FunVal) fun1 = NEW(FunVal)("x", body1, Env::empty);
    PTR(FunVal) fun2 = NEW(FunVal)("x", body2, Env::empty);

    REQUIRE_THROWS_AS(fun1->addTo(fun2), std::runtime_error);

    // Clean up the created expression objects
    // delete body1;
    // delete body2;
}

TEST_CASE("FunVal multiplication throws exception") {
    // Test multiplying two FunVal objects, which should always throw an exception
    PTR(Expr) body1 = NEW(NumExpr)(5);
    PTR(Expr) body2 = NEW(NumExpr)(10);
    FunVal fun1("x", body1, Env::empty);
    PTR(FunVal) fun2 = NEW(FunVal)("x", body2, Env::empty);

    REQUIRE_THROWS_AS(fun1.multWith(fun2), std::runtime_error);

    // Clean up the created expression objects
    // delete body1;
    // delete body2;
}

TEST_CASE("FunVal toString method") {
    // Test the `toString` method for FunVal
    PTR(Expr) body1 = NEW(NumExpr)(42);
    PTR(FunVal) fun1 = NEW(FunVal)("x", body1, Env::empty);

    // Validate the string representation of FunVal
    REQUIRE(fun1->toString() == "_fun (x) 42 ");

    // Clean up the created expression object
    // delete body1;
}

// TEST_CASE("FunVal toExpr method") {
//     // Test the `toExpr` method, which should return a corresponding FunExpr
//     PTR(Expr) body1 = NEW(NumExpr)(42);
//     PTR(FunVal) fun1 = NEW(FunVal)("x", body1);
//
//     PTR(Expr) expr = fun1->toExpr();
//     REQUIRE(CAST(FunExpr)(expr) != nullptr);
//
//     // Clean up the created expression objects
//     // delete body1;
//     // delete expr;
// }

TEST_CASE("FunVal isTrue throws exception") {
    // Test the `isTrue` method, which should always throw an exception for FunVal
    PTR(Expr) body1 = NEW(NumExpr)(42);
    PTR(FunVal) fun1 = NEW(FunVal)("x", body1, Env::empty);

    REQUIRE_THROWS_AS(fun1->isTrue(), std::runtime_error);

    // Clean up the created expression object
    // delete body1;
}

TEST_CASE("FunVal call method") {
    // Test calling a FunVal with an argument
    PTR(Expr) body1 = NEW(NumExpr)(42);
    FunVal fun1("x", body1, Env::empty);

    // Create an argument for the function call
    PTR(NumVal) arg = NEW(NumVal)(5);

    // Call the function with the argument
    PTR(Val) result = fun1.call(arg);

    // Check if the result is of type NumVal
    REQUIRE(CAST(NumVal)(result) != nullptr);

    // Validate the result value (this would depend on how the `subst` and `interp` methods work)
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "42");

    // Clean up the result and expression objects
    // delete result;
    // delete body1;
}

TEST_CASE("FunVal call method with substituted argument") {
    // Test calling a FunVal with an argument and verifying substitution
    PTR(Expr) body1 = NEW(NumExpr)(0);  // Just an example, actual behavior depends on how `subst` works
    FunVal fun1("x", body1, Env::empty);

    // Create an argument for the function call
    PTR(NumVal) arg = NEW(NumVal)(5);

    // Simulate substitution and calling the function
    PTR(Val) result = fun1.call(arg);

    // Check the result of calling the function
    // For now, assuming `call` simply returns the body value (this will change depending on your implementation)
    REQUIRE(CAST(NumVal)(result) != nullptr);
    PTR(NumVal) numResult = CAST(NumVal)(result);
    REQUIRE(numResult->toString() == "0");  // Replace this with expected result based on your substitution logic

    // Clean up the result and expression objects
    // delete result;
    // delete body1;
}