#include <fstream>
#include <iostream>
// ** Generated by chatgpt
int main() {
    // Open the file for writing. If the file doesn't exist, it will be created.
    std::ofstream outputFile("numbers.txt");

    // Check if the file was successfully opened
    if (!outputFile) {
        std::cerr << "Error opening file!" << std::endl;
        return 1;  // Return a non-zero value to indicate an error
    }

    // Use a for loop to write numbers 1 to 1000 to the file
    for (int i = 1; i <= 5000000; ++i) {
        outputFile << i << std::endl;  // Write the number followed by a newline
    }

    // Close the file after writing
    outputFile.close();

    return 0;  // Return 0 to indicate successful execution
}